
variables:
  GIT_STRATEGY: none

stages:
    - test

phpcs:
  before_script:
    - cd /home/ubuntu/builds/scripts/worksuite/Recruit
  stage: test
  script:
    - git reset --hard HEAD
    - git fetch
    - git checkout $CI_BUILD_REF_NAME
    - git merge origin/$CI_BUILD_REF_NAME
    - phpcs --standard=~/.composer/vendor/froiden/php_standard/ruleset.xml DataTables/ Console/ Entities/ Http/ Listeners/ Observers Routes Providers
